return {}
-- {
-- 	"greggh/claude-code.nvim",
-- 	dependencies = {
-- 		"nvim-lua/plenary.nvim", -- Required for git operations
-- 	},
-- 	config = function()
-- 		require("claude-code").setup({
-- 			keymaps = {
-- 				toggle = {
-- 					normal = "<C-t>", -- Use Ctrl+T in normal mode
-- 					terminal = "<C-t>", -- Use Ctrl+T in terminal mode
-- 				},
-- 			},
-- 			window = {
-- 				position = "float",
-- 				float = {
-- 					width = "90%", -- Take up 90% of the editor width
-- 					height = "90%", -- Take up 90% of the editor height
-- 					row = "center", -- Center vertically
-- 					col = "center", -- Center horizontally
-- 					relative = "editor",
-- 					border = "double", -- Use double border style
-- 				},
-- 			},
-- 		})
-- 	end,
-- }
